# Generated by Django 4.1.4 on 2022-12-24 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_urldatabase_url_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldatabase',
            name='URL_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='URL_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Shortened_URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=700)),
                ('short_url', models.CharField(max_length=100)),
                ('URL_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='URL_user_main', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
