# Generated by Django 4.1.4 on 2022-12-24 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_urldatabase_url_user_shortened_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urldatabase',
            name='URL_user',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='URLDatabase',
        ),
    ]
